name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request: null
  workflow_dispatch: null

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      APP_URL: ${{ secrets.APP_URL }}
      GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
      GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
      

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 22  # Set Node.js version

      - name: Install dependencies
        run: npm install --legacy-peer-deps  # Avoid dependency conflicts

      - name: Install Playwright Browsers
        run: npx playwright install chromium firefox webkit

      - name: Debug environment
        run: env | sort  # Prints all environment variables (except secrets)

      - name: Run tests
        run: npm run e2e -- --debug --trace # Run tests in debug mode

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
